# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

stages:
 - first

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.

variables:
    JIRA_PASS: $JIRA_PASS
    JIRA_USER: $JIRA_USER
    JOW_HOOK: $JOW_SLACK
    CUR_HOOK: $CUR_SLACK
    DAM_HOOK: $DAM_SLACK
    PRI_HOOK: $PRI_SLACK

before_script:
    - echo $PATH
    - apt-get update -qq && apt-get install -y -qq curl python3.8 python3-pip
    - python3 -v
    - pip3 install jira
    - pip3 install datetime
    - pip3 install python-dotenv

mrbtk:
  stage: first
  tags:
   - autoscale
  script:
    - python3 priority_report.py ${TOCURATORS}
